version: 2.1

jobs:
  build:
    docker:
        - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - run:
          name: "Run Build App"
          command: dotnet.exe build
      - run:
          name: "Run App"
          command: dotnet run 
