name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Build with dotnet 2
      run: dotnet build
    - name: Run
      run: dotnet run --project ./ConsoleApp1
    - name: Test
      run: dotnet test ./NUnitTestProject1
